<a href="https://colab.research.google.com/github/duaanoor31/Numpy-Assignment/blob/main/Numpy_Core_Operation_Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Duaa Abdul Qadir** :
**Roll No 886550**

In [ ]:
import numpy as np

In [ ]:
# STUDENTS PRACTICE TASKS
#Task 1
marks = np.array([10, 20, 30, 40, 50])
print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))

150
30.0
50
10


In [ ]:
#Task 2
marks = np.array([45, 80, 30, 90, 55, 20])

result = marks[marks >= 50]

print(result)

[80 90 55]


In [ ]:
#Task 3
num = np.array([1, 2, 3, 4, 5, 6])

result = num.reshape(2, 3)

print(result)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
#Task 4
marks = np.random.randint(40, 101, 10)
print(marks)
print("Marks:", marks)
print("Average:", np.mean(marks))
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))

[74 65 69 94 45 44 66 46 92 65]
Marks: [74 65 69 94 45 44 66 46 92 65]
Average: 66.0
Highest Marks: 94
Lowest Marks: 44


In [ ]:
#Task 5
marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])
passed_marks = marks[marks >= 50]
failed_marks = marks[marks < 50]
print("Passed marks:", passed_marks)
print("Failed marks:", failed_marks)
print("Number of passed students:", len(passed_marks))
print("Number of failed students:", len(failed_marks))

Passed marks: [67 89 90 70 58]
Failed marks: [35 45 22]
Number of passed students: 5
Number of failed students: 3
