<a href="https://colab.research.google.com/github/duaanoor31/Numpy-Assignment/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Duaa Abdul Qadir** :
**Roll NO** 886550


In [ ]:
import numpy as np

In [ ]:
# 2 Python List VS Numpy Array:
import numpy as np
marks = np.array([70, 80, 90, 60])
print(marks)

[70 80 90 60]


In [ ]:
#3 Creating Numpy Array:
#one dimensional array:
numbers = np.array([10, 20, 30, 40])
print(numbers)
#Two dimensional array:
marks = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [88, 92, 95]
])

print(marks)

[10 20 30 40]
[[70 80 90]
 [60 75 85]
 [88 92 95]]


In [ ]:
# 4 important array properties:
data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(data.ndim)
print(data.shape)
print(data.size)
print(data.dtype)


2
(2, 3)
6
int64


In [ ]:
# 5 Indenxing:
numbers = np.array([10, 20, 30, 40, 50])
print(numbers[3])
print(numbers[-1])

40
50


In [ ]:
# 6 Indexing in a 2D Array:
marks = np.array([
    [70, 80, 90],
    [60, 75, 85]
])
print(marks[0, 2])

90


In [ ]:
# 7 Slicing
numbers = np.array([10, 20, 30, 40, 50])
print(numbers[0:4])

[10 20 30 40]


In [ ]:
# 8 vectorized operation:
numbers = np.array([10, 20, 30, 40])
print(numbers + 5)
print(numbers * 2)
print(numbers - 6)
print(numbers / 4)

[15 25 35 45]
[20 40 60 80]
[ 4 14 24 34]
[ 2.5  5.   7.5 10. ]


In [ ]:
# 9 operation between two array:
a = np.array([10, 40, 30])
b = np.array([1, 2, 3])
print(a + b)
print(a * b)

[11 42 33]
[10 80 90]


In [ ]:
# 10 Mathematical Functions
numbers = np.array([4, 9, 16, 25])
print(np.sqrt(numbers))
numbers = np.array([2, 5, 4])
print(np.power(numbers, 2))
numbers = np.array([-10, -5, -7, 8])
print(np.abs(numbers))
numbers = np.array([4.2, 5.7, 8.9])
print(np.round(numbers))

[2. 3. 4. 5.]
[ 4 25 16]
[10  5  7  8]
[4. 6. 9.]


In [ ]:
# 11 Aggregation function:
marks = np.array([70, 85, 60, 95, 80])
print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.median(marks))
print(np.std(marks))


390
78.0
95
60
80.0
12.083045973594572


In [ ]:
#12 Condition in numpy:
marks = np.array([30, 50, 80, 45, 90, 20])
print(marks >= 50)

[False  True  True False  True False]


In [ ]:
#13 Filtering Data:
marks = np.array([30, 55, 82, 98, 90, 30])
passed = marks[marks >= 50]
print(passed)
failed = marks[marks < 50]
print(failed)

[55 82 98 90]
[30 30]


In [ ]:
# 14 Reshape:
numbers = np.array([1, 2, 3, 4, 5, 6])
new_array = numbers.reshape(2, 3)
print(new_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
#15 Flatten:
data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(data.flatten())

[1 2 3 4 5 6]


In [ ]:
#16 usefull numpy function:
print(np.zeros(10))
print(np.ones(6))
print(np.arange(1, 21))
print(np.arange(0, 21, 2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
#17 Random Numbers:
marks = np.random.randint(40, 100, 10)
print(marks)

[97 58 52 85 47 95 80 65 70 58]
